{
 "title": "SRI benchmarking tool",
 "description": "Benchmarking tool to measure Stratum V2 and Stratum (V1) protocol performances in different contexts ",
 "tags": [
  "docker",
  "prometheus, ",
  "node-exporter",
  "cadvisor"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Shares, blocks and templates stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "SV1 vs SV2 - shares acceptance rate",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sv1_submitted_shares", "legendFormat": "SV1 submitted shares" },
    { "expr": "sv1_valid_shares", "legendFormat": "SV1 valid shares" },
    {
     "expr": "(sv1_valid_shares * 100) / sv1_submitted_shares",
     "legendFormat": "SV1 acceptance rate"
    },
    { "expr": "sv2_submitted_shares", "legendFormat": "SV2 submitted shares" },
    { "expr": "sv2_valid_shares", "legendFormat": "SV2 valid shares" },
    {
     "expr": "(sv2_valid_shares * 100) / sv2_submitted_shares",
     "legendFormat": "SV2 acceptance rate"
    }
   ]
  },
  {
   "title": "SV1 vs SV2 - block template value",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sats" } },
   "targets": [
    { "expr": "sv1_block_template_value", "legendFormat": "SV1 - block template value" },
    { "expr": "sv2_block_template_value", "legendFormat": "SV2 - block template value" }
   ]
  },
  {
   "title": "SV2 - block template value - comparison with mined blocks on the network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "sats" } },
   "targets": [
    { "expr": "last_block_mined_value", "legendFormat": "Network - block template value" },
    { "expr": "last_sv2_template_value ", "legendFormat": "SV2 - block template value" },
    {
     "expr": "(last_sv2_template_value - last_block_mined_value) / last_block_mined_value * 100",
     "legendFormat": "SV2 delta %"
    }
   ]
  },
  { "title": "Latency and time measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Average latency with major pools (RTT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "average_pool_subscription_latency_milliseconds",
     "legendFormat": "Average latency with major pools (RTT)"
    }
   ]
  },
  {
   "title": "SV1 vs SV2 - time to get a new job from Pool",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sv1_new_job_latency",
     "legendFormat": "SV1 - time to get a new job from Pool"
    },
    {
     "expr": "new_job_pool_new_template",
     "legendFormat": "SV2 - time to get a new job from Pool"
    }
   ]
  },
  {
   "title": "SV1 vs SV2 - time to get a new job (after a new block found) from Pool",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sv1_new_job_prev_hash_latency",
     "legendFormat": "SV1 - time to get a new job (after a new block found) from Pool"
    },
    {
     "expr": "new_job_prev_hash_through_sv2_pool",
     "legendFormat": "SV2 - time to get a new job (after a new block found) from Pool"
    }
   ]
  },
  {
   "title": "SV1 vs SV2 - block propagation time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "block_propagation_time_through_sv1_pool",
     "legendFormat": "SV1 - block propagation time"
    },
    {
     "expr": "block_propagation_time_through_sv2_pool",
     "legendFormat": "SV2 - block propagation time"
    }
   ]
  },
  {
   "title": "Bandwidth Usage - Mining Farm Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 }
  },
  {
   "title": "SV1 vs SV2 - Network Tx (farm level)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (id, name) (ntm_bytes_total{dst=\"10.5.0.8\", src=\"10.5.0.19\"})",
     "legendFormat": "SV1 (farm net interface)"
    },
    {
     "expr": "sum by (id, name) (ntm_bytes_total{src=\"10.5.0.17\", dst=\"10.5.0.4\"})",
     "legendFormat": "SV2 (translator)"
    }
   ]
  },
  {
   "title": "SV1 vs SV2 - Network Rx  (farm level)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (id, name) (ntm_bytes_total{src=\"10.5.0.8\", dst=\"10.5.0.19\"})",
     "legendFormat": "SV1 (farm net interface)"
    },
    {
     "expr": "sum by (id, name) (ntm_bytes_total{dst=\"10.5.0.17\", src=\"10.5.0.4\"})",
     "legendFormat": "SV2 (translator)"
    }
   ]
  },
  { "title": "Bandwidth Usage - Pool Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "SV1 vs SV2 - Network Tx (pool level)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (id, name) (ntm_bytes_total{src=\"10.5.0.8\", dst=\"10.5.0.19\"})",
     "legendFormat": "SV1 (pool server only)"
    },
    {
     "expr": "sum by (id, name) (ntm_bytes_total{src=\"10.5.0.4\", dst=\"10.5.0.17\"})",
     "legendFormat": "SV2 (pool server only)"
    }
   ]
  },
  {
   "title": "SV1 vs SV2 - Network Rx (pool level)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (id, name) (ntm_bytes_total{dst=\"10.5.0.8\", src=\"10.5.0.19\"})",
     "legendFormat": "SV1 (pool server only)"
    },
    {
     "expr": "sum by (id, name) (ntm_bytes_total{dst=\"10.5.0.4\", src=\"10.5.0.17\"})",
     "legendFormat": "SV2 (pool server only)"
    }
   ]
  },
  {
   "title": "SV1 - Network Tx (pool level)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (id, name) (ntm_bytes_total{src=\"10.5.0.8\", dst=\"10.5.0.19\"})",
     "legendFormat": "Pool"
    },
    {
     "expr": "sum by (id, name) (ntm_bytes_total{src=\"10.5.0.16\", dst!=\"192.168.65.1\", dst!=\"10.5.0.8\", dst!=\"10.5.0.21\", dst!=\"192.168.65.7\"})",
     "legendFormat": "Bitcoin Node"
    }
   ]
  },
  {
   "title": "SV2 - Network Tx (pool level)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (id, name) (ntm_bytes_total{src=\"10.5.0.4\", dst=\"10.5.0.17\"})",
     "legendFormat": "Pool"
    },
    {
     "expr": "sum by (id, name) (ntm_bytes_total{src=\"10.5.0.2\", dst!=\"192.168.65.1\", dst!=\"10.5.0.4\", dst!=\"10.5.0.5\", dst!=\"10.5.0.20\", dst!=\"192.168.65.7\"})",
     "legendFormat": "Template Provider (TP)"
    }
   ]
  },
  {
   "title": "SV1 - Network Rx (pool level)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (id, name) (ntm_bytes_total{dst=\"10.5.0.8\", src=\"10.5.0.19\"})",
     "legendFormat": "Pool"
    },
    {
     "expr": "sum by (id, name) (ntm_bytes_total{dst=\"10.5.0.16\", src!=\"192.168.65.1\", src!=\"10.5.0.8\", src!=\"10.5.0.21\", src!=\"192.168.65.7\"})",
     "legendFormat": "Bitcoin Node"
    }
   ]
  },
  {
   "title": "SV2 - Network Rx (pool level)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (id, name) (ntm_bytes_total{dst=\"10.5.0.4\", src=\"10.5.0.17\"})",
     "legendFormat": "Pool"
    },
    {
     "expr": "sum by (id, name) (ntm_bytes_total{dst=\"10.5.0.2\", src!=\"192.168.65.1\", src!=\"10.5.0.4\", src!=\"10.5.0.5\", src!=\"10.5.0.20\", src!=\"192.168.65.7\"})",
     "legendFormat": "Template Provider (TP)"
    }
   ]
  },
  {
   "title": "SV1 roles performances (per container)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 }
  },
  {
   "title": "Pool Roles (SV1) - CPU Usage ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"sv1-pool\"}[1m])) by (id, name) \n",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"sv1-node-pool-side\"}[1m])) by (id, name) \n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Pool Roles (SV1) - Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"sv1-pool\"}\n",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "container_memory_usage_bytes{name=~\"sv1-node-pool-side\"}\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Pool Roles (SV1) - Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(container_network_transmit_bytes_total{name=~\"sv1-pool\"}[5m]))\n",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (id, name) (irate(container_network_transmit_bytes_total{name=~\"sv1-node-pool-side\"}[5m]))\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Pool Roles (SV1) - Network Rx ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(container_network_receive_bytes_total{name=~\"sv1-pool\"}[5m]))\n",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (id, name) (irate(container_network_receive_bytes_total{name=~\"sv1-node-pool-side\"}[5m]))\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "SV2 roles performances (per container)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pool Roles (SV2) - CPU Usage ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"sv2-tp-pool-side|sv2-pool|sv2-jds\"}[1m])) by (id, name) \n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Pool Roles (SV2) - Memory Usage ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"sv2-tp-pool-side|sv2-pool|sv2-jds\"}\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Pool Roles (SV2) - Network Tx ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(container_network_transmit_bytes_total{name=~\"sv2-tp-pool-side|sv2-pool|sv2-jds\"}[10s]))\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Pool Roles (SV2) - Network Rx ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(container_network_receive_bytes_total{name=~\"sv2-tp-pool-side|sv2-pool|sv2-jds\"}[10s]))\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Miner Roles (SV2) - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"sv2-tp-miner-side|sv2-jdc|sv2-translator\"}[1m])) by (id, name) \n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Miner Roles (SV2) - Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"sv2-tp-miner-side|sv2-jdc|sv2-translator\"}\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Miner Roles (SV2) - Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(container_network_transmit_bytes_total{name=~\"sv2-translator\"}[20s]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Miner Roles (SV2) - Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(container_network_receive_bytes_total{name=~\"sv2-tp-miner-side|sv2-jdc|sv2-translator\"}[10s]))\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Host Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{mode=\"idle\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( node_filesystem_avail_bytes {mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Node Mermory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Available Memory"
    }
   ]
  }
 ]
}